-- Allow comma-separated work types in registered_hours
-- e.g. 'DIRECT_SESSION,DOCUMENTATION'
ALTER TABLE registered_hours DROP CONSTRAINT IF EXISTS valid_type;

ALTER TABLE registered_hours ADD CONSTRAINT valid_types CHECK (
  work_type ~ '^(DIRECT_SESSION|TRANSPORT|DOCUMENTATION|COORDINATION|CRISIS_RESPONSE|TRAINING|OTHER)(,(DIRECT_SESSION|TRANSPORT|DOCUMENTATION|COORDINATION|CRISIS_RESPONSE|TRAINING|OTHER))*$'
);
