-- =============================================================================
-- ADDITIVE ONLY: corrects three published /indsigt articles that still
-- presented Servicelovens §52 as the current legal basis for children's
-- kontaktperson cases. §52 was replaced by §32 i barnets lov on 1 January
-- 2024 (see the already-correct article 'paragraf-32-barnets-lov-kontaktperson'
-- from migration 20260909000000, which these three contradicted).
-- No rows added or removed, no schema change — only content of existing
-- rows is corrected. Slugs are kept unchanged to preserve existing URLs/SEO.
-- Safe to re-run.
-- =============================================================================

BEGIN;

-- Article 1: 'serviceloven-paragraf-52-og-85'
-- Was entirely built around §52 as the current basis for children's cases.
-- Rewritten around barnets lov §32 (children) + servicelovens §85 (adults).
UPDATE public.cms_articles SET
  title = 'Barnets lov §32 og servicelovens §85 — en introduktion til kontaktpersonordninger',
  excerpt = 'Lovgivningen bag kontaktpersonforløb er §32 i barnets lov for børn og unge under 18 år, og §85 i serviceloven for voksne. Her er en faglig introduktion til begge.',
  content = E'Lovgivningen bag kontaktpersonforløb afhænger af borgerens alder: **§32 i barnets lov** for børn og unge under 18 år, og **§85 i serviceloven** for voksne. Her er en faglig introduktion til begge — og til hvorfor børneområdet skiftede lovgrundlag i 2024.\n\n## Barnets lov §32 — foranstaltninger for børn og unge\n\nFra 1. januar 2024 afløste barnets lov serviceloven som hjemmel for støttende foranstaltninger til børn og unge under 18 år. §32 giver kommunalbestyrelsen mulighed for at iværksætte disse foranstaltninger, "når det er nødvendigt af hensyn til barnets eller den unges behov og udvikling" — herunder **udpegning af en fast kontaktperson**.\n\nKontaktperson under §32 bruges typisk, når den unge har behov for en stabil, fast voksen relation — men ikke er i en situation, der kræver anbringelse.\n\n§32-foranstaltninger kræver som udgangspunkt en børnefaglig undersøgelse og forældrenes samtykke — samme forudsætninger som under den tidligere §52 i serviceloven, som §32 erstattede.\n\n## Servicelovens §85 — støtte til voksne med nedsat funktionsevne\n\n§85 giver kommunen mulighed for at yde hjælp, omsorg eller støtte til voksne med **nedsat psykisk eller fysisk funktionsevne**. Indsatsen er fleksibel og kan tilpasses den enkelte borgers behov.\n\n§85 kan bevilges til personlig hjælp og støtte, hjælp til kommunikation og socialpædagogisk bistand til at klare dagligdagen og fastholde boligen.\n\n§85 kræver borgerens ansøgning og en kommunal vurdering af borgerens behov og funktionsevnenedsættelse.\n\n## Lovgivningens rammer for private leverandører\n\nKommunen kan anvende private leverandører — som Kursskifte — til at levere indsatser under begge lovgrundlag. Private leverandører er underlagt samme kvalitetskrav som kommunale tilbud.\n\nKursskifte leverer indsatser til kommuner i Nordjylland og bistår med den administrative koordination, dokumentation og opfølgning, der er forbundet med forløbet.\n\n## Hvad kommunen skal vide\n\nLovgivningen giver kommunen relativt vide rammer for, hvad der kan bevilges og til hvem. Den afgørende faktor er den individuelle behovsvurdering — og den skal have et fagligt fundament. Sørg for, at nye bevillinger og sagsdokumenter til børn og unge refererer til **barnets lov §32**, ikke den tidligere §52. Kursskifte bistår kommunens socialrådgivere med faglig information om matchning og kvalitetssikring inden for lovgivningens rammer.',
  tags = ARRAY['barnets lov', '§32', 'serviceloven', '§85', 'lovgivning', 'kontaktpersonordning'],
  meta_title = 'Barnets lov §32 og servicelovens §85 — introduktion til kontaktpersonordninger — Kursskifte',
  meta_description = 'Introduktion til barnets lov §32 (børn og unge) og servicelovens §85 (voksne) som hjemmel for kontaktpersonforløb: formål, betingelser og rammer for private leverandører.'
WHERE slug = 'serviceloven-paragraf-52-og-85';

-- Article 2: 'ekstern-vs-kommunal-kontaktperson'
-- Only the closing paragraph named §52 as a current legal basis.
UPDATE public.cms_articles SET
  content = E'Kommuner kan vælge mellem to overordnede modeller for levering af kontaktpersonforløb: den kommunale model, hvor fagpersonen er ansat i kommunen, og den eksterne model, hvor en privat leverandør stiller fagpersonen til rådighed. Begge modeller har fordele og ulemper.\n\n## Den kommunale kontaktperson\n\nI den kommunale model er kontaktpersonen ansat direkte i kommunen — typisk i socialforvaltningen, et familiecenter eller et ungehus.\n\n**Fordele:**\n- Tæt integration med kommunens øvrige indsatser og systemer\n- Lettere koordination med socialrådgiver og anden kommunal indsats\n- Direkte adgang til kommunale ressourcer og netværk\n\n**Ulemper:**\n- Begrænset kapacitet ved spidsbelastning\n- Svært at matche specialiserede kompetencer til specifikke borgere\n- Kommunale medarbejdere er ikke altid tilgængelige uden for normal arbejdstid\n- Rekrutteringsprocesser er langsomme\n\n## Den eksterne kontaktperson\n\nI den eksterne model er kontaktpersonen en selvstændig fagperson eller ansat hos en privat leverandør.\n\n**Fordele:**\n- Adgang til specialiserede kompetencer kommunen ikke selv råder over\n- Fleksibel kapacitet — kan skaleres op og ned afhængigt af behovet\n- Fagpersoner med specialer inden for fx misbrug, psykiatri eller specifikke aldersgrupper\n- Hurtigere opstart ved kendte leverandører\n\n**Ulemper:**\n- Kræver kommunal godkendelse og administrativ opsætning\n- Kræver aktiv koordination og tilsyn fra kommunens side\n\n## Hvornår bruges hvilken model?\n\nDen kommunale model egner sig til standardforløb inden for kommunens kernekompetencer og borgere med behov for tæt kommunal koordination.\n\nDen eksterne model egner sig til specialiserede forløb, kapacitetsproblemer i kommunen, akutte behov eller borgere, der vil profitere af en vis afstand til det kommunale system.\n\nMange kommuner bruger i praksis begge modeller side om side.\n\n## Kursskiftes rolle\n\nKursskifte er en ekstern leverandør, der matcher kommuner med kvalitetssikrede kontaktpersoner til forløb under barnets lov §32 og servicelovens §85. Vi håndterer matchning, dokumentation og koordination som en integreret service — ikke blot et vikarbureau.'
WHERE slug = 'ekstern-vs-kommunal-kontaktperson';

-- Article 3: 'mentor-vs-kontaktperson'
-- Three inline mentions of §52 as a current, valid legal basis.
UPDATE public.cms_articles SET
  content = E'Termerne "kontaktperson" og "mentor" bruges sommetider om hinanden, men de dækker over forskelligartede indsatser med forskellige formål, lovhjemler og faglige profiler. Klarhed om forskellen hjælper kommunen med at vælge den rette indsats.\n\n## Hvad er en kontaktperson?\n\nEn kontaktperson er en uddannet fagperson, typisk tilknyttet via kommunen eller en godkendt leverandør, der iværksætter en **socialfaglig indsats** baseret på en kommunal behovsvurdering. Indsatsen er hjemlet i barnets lov §32 (børn og unge under 18 år) eller servicelovens §85 (voksne) og finansieres af kommunen.\n\nKontaktpersonens rolle er at skabe en stabil, tillidsfuld relation, der understøtter borgerens sociale og personlige udvikling over tid. Indsatsen er professionel og dokumenteret.\n\n## Hvad er en mentor?\n\nEn mentor er typisk en frivillig eller lønnet person med relevant livserfaring eller faglig baggrund, der tilbyder **personlig guidning og rådgivning** til en ung i en konkret situation. Mentorordninger er ofte organiseret af NGO''er, uddannelsesinstitutioner eller private organisationer.\n\nMentorordninger er ikke hjemlet i Serviceloven og finansieres ikke som sociale indsatser.\n\n## Nøgleforskelle\n\n**Kontaktperson:** Lovhjemmel i barnets lov §32 (børn/unge) eller servicelovens §85 (voksne). Kommunalt finansieret. Kræver uddannelse. Obligatorisk dokumentation. Formål er socialfaglig indsats. Typisk 6–24 måneder.\n\n**Mentor:** Ingen specifik lovhjemmel. Typisk fondsstøtte eller frivillig. Varierende uddannelseskrav. Formål er personlig guidning og netværk. Varierende varighed.\n\n## Hvornår er hvad det rigtige valg?\n\n**Kontaktperson:** Når borgeren har behov for professionel socialfaglig indsats, er i en sårbar situation, der kræver faglig vurdering og dokumentation, eller når kommunen har en myndighedsforpligtelse.\n\n**Mentor:** Når en ung, der generelt klarer sig, har behov for personlig inspiration, netværk eller rollemodel — men ikke nødvendigvis professionel socialfaglig indsats.\n\nI mange tilfælde kan de to indsatser supplere hinanden: kontaktpersonen er den professionelle fagperson, og mentoren er en rollemodel fra uddannelse eller erhverv.\n\n## Kursskiftes specialisering\n\nKursskifte arbejder udelukkende med professionelle kontaktpersonforløb hjemlet i barnets lov og serviceloven. Vi er eksperter i matchning og koordination af socialfaglige indsatser.'
WHERE slug = 'mentor-vs-kontaktperson';

COMMIT;
